uv example implementation
BharatKalluri/cleanmail pull request #4
Opened 2024-11-04 12:51 UTC by benomahony

2024-11-05 05:01 UTC, BharatKalluri requested changes

2024-11-05 05:01 UTC, BharatKalluri commented on README.md
> +   streamlit run main.py`
Let's use `uv run` so that we don't have to worry about activating the virtual env. with that we can remove the above step from readme

2024-11-05 05:01 UTC, BharatKalluri commented on pyproject.toml
> +description = "Add your description here"
please borrow the description from the readme.md

`A tool to quickly clean up your email inbox!`

2024-11-05 05:01 UTC, BharatKalluri commented
Thanks for the PR @benomahony !

could you also update the docker file so that docker also uses UV?

2024-11-05 07:50 UTC, BharatKalluri commented
lgtm, thanks for the contribution!

2024-11-05 07:50 UTC, merged

2025-01-06 09:40 UTC, ok-eric commented
Really cool to see this go from a comment thread elsewhere to a functioning feature. Love you guys keep going